import 'package:flutter/material.dart';


// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Onboirding3(),
        ]),
      ),
    );
  }
}

class Onboirding3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.00, -1.00),
              end: Alignment(0, 1),
              colors: [Color(0xFF6D64FF), Color(0xFF8A83FF)],
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: -39.56,
                top: 1003.19,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-2),
                  child: Container(
                    padding: const EdgeInsets.only(
                      top: 62.92,
                      left: 46.55,
                      right: 123.11,
                      bottom: 47.94,
                    ),
                    clipBehavior: Clip.antiAlias,
                    decoration: BoxDecoration(color: Colors.white.withOpacity(0)),
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.end,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.19),
                          child: Container(
                            width: 233.05,
                            height: 273.83,
                            child: Stack(children: [

                                ]),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 946,
                child: Container(
                  width: 335,
                  height: 90,
                  decoration: BoxDecoration(
                    color: Colors.white,
                    border: Border(
                      left: BorderSide(
                        strokeAlign: BorderSide.strokeAlignCenter,
                      ),
                      top: BorderSide(
                        strokeAlign: BorderSide.strokeAlignCenter,
                      ),
                      right: BorderSide(
                        strokeAlign: BorderSide.strokeAlignCenter,
                      ),
                      bottom: BorderSide(
                        strokeAlign: BorderSide.strokeAlignCenter,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 973,
                child: Container(
                  width: 36,
                  height: 36,
                  decoration: ShapeDecoration(
                    color: Color(0xFF6847FE),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 986,
                child: Container(
                  width: 12,
                  height: 11.37,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/12x11"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 299,
                top: 963,
                child: Text(
                  '-£47,098',
                  textAlign: TextAlign.right,
                  style: TextStyle(
                    color: Color(0xFFFF3572),
                    fontSize: 16,
                    fontFamily: 'Abel',
                    fontWeight: FontWeight.w400,
                    height: 57,
                    letterSpacing: -0.12,
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 976,
                child: SizedBox(
                  width: 148,
                  height: 36,
                  child: Text(
                    'Wallet account deposit ',
                    style: TextStyle(
                      color: Color(0xFFA5ADC6),
                      fontSize: 14,
                      fontFamily: 'Abel',
                      fontWeight: FontWeight.w400,
                      height: 57,
                      letterSpacing: -0.11,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 950,
                child: Text(
                  'Wallet withdraw',
                  style: TextStyle(
                    color: Color(0xFF242A3E),
                    fontSize: 15,
                    fontFamily: 'Abel',
                    fontWeight: FontWeight.w400,
                    height: 57,
                    letterSpacing: -0.12,
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 1036,
                child: Container(
                  width: 335,
                  height: 90,
                  decoration: BoxDecoration(
                    color: Colors.white,
                    border: Border(
                      left: BorderSide(
                        strokeAlign: BorderSide.strokeAlignCenter,
                      ),
                      top: BorderSide(
                        strokeAlign: BorderSide.strokeAlignCenter,
                      ),
                      right: BorderSide(
                        strokeAlign: BorderSide.strokeAlignCenter,
                      ),
                      bottom: BorderSide(
                        strokeAlign: BorderSide.strokeAlignCenter,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 1062,
                child: Container(
                  width: 38,
                  height: 38,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/38x38"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 1040,
                child: Text(
                  'Dell technology stock',
                  style: TextStyle(
                    color: Color(0xFF242A3E),
                    fontSize: 15,
                    fontFamily: 'Abel',
                    fontWeight: FontWeight.w400,
                    height: 57,
                    letterSpacing: -0.12,
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 1064,
                child: SizedBox(
                  width: 148,
                  height: 38,
                  child: Text(
                    'NYSE: DELL',
                    style: TextStyle(
                      color: Color(0xFFA5ADC6),
                      fontSize: 14,
                      fontFamily: 'Abel',
                      fontWeight: FontWeight.w400,
                      height: 57,
                      letterSpacing: -0.11,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 291,
                top: 1053,
                child: Text(
                  '-\$150,901',
                  textAlign: TextAlign.right,
                  style: TextStyle(
                    color: Color(0xFFFF3572),
                    fontSize: 16,
                    fontFamily: 'Abel',
                    fontWeight: FontWeight.w400,
                    height: 57,
                    letterSpacing: -0.12,
                  ),
                ),
              ),
              Positioned(
                left: 396,
                top: 727,
                child: SizedBox(
                  width: 82,
                  height: 21,
                  child: Text(
                    'Mastercard',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Avenir',
                      fontWeight: FontWeight.w500,
                      letterSpacing: -0.07,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 530,
                top: 174,
                child: SizedBox(
                  width: 95,
                  height: 23,
                  child: Text(
                    '******',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Avenir',
                      fontWeight: FontWeight.w800,
                      height: 40,
                      letterSpacing: 0.62,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 595,
                top: 167,
                child: SizedBox(
                  width: 96,
                  height: 25,
                  child: Text(
                    '3443',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 24,
                      fontFamily: 'Avenir',
                      fontWeight: FontWeight.w800,
                      height: 40,
                      letterSpacing: 0.62,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 663,
                top: 353,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-3.14),
                  child: Container(
                    width: 68,
                    height: 60,
                    decoration: ShapeDecoration(
                      color: Colors.white,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.only(
                          topLeft: Radius.circular(23),
                          topRight: Radius.circular(21),
                          bottomRight: Radius.circular(22),
                        ),
                      ),
                      shadows: [
                        BoxShadow(
                          color: Color(0x00000000),
                          blurRadius: 30,
                          offset: Offset(10, 20),
                          spreadRadius: 0,
                        )
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 590,
                top: 313,
                child: SizedBox(
                  width: 79,
                  height: 53,
                  child: Text(
                    'arrow-right',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF252527),
                      fontSize: 18,
                      fontFamily: 'Font Awesome 5 Pro',
                      fontWeight: FontWeight.w300,
                      letterSpacing: 0.16,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 421,
                top: 738,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-3.14),
                  child: Container(
                    width: 31,
                    height: 27,
                    decoration: ShapeDecoration(
                      color: Color(0xFFFCF2E1),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(14),
                      ),
                      shadows: [
                        BoxShadow(
                          color: Color(0x2B000000),
                          blurRadius: 80,
                          offset: Offset(10, 20),
                          spreadRadius: 0,
                        )
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 391,
                top: 710,
                child: SizedBox(
                  width: 28,
                  height: 21,
                  child: Text(
                    '+',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF120B2D),
                      fontSize: 18,
                      fontFamily: 'Avenir',
                      fontWeight: FontWeight.w500,
                      height: 20,
                      letterSpacing: 0.11,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 388,
                top: 792,
                child: Container(
                  width: 8,
                  height: 8,
                  decoration: ShapeDecoration(
                    shape: OvalBorder(
                      side: BorderSide(width: 1, color: Color(0xFFABA0EF)),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 851,
                child: SizedBox(
                  width: 155,
                  height: 94,
                  child: Text(
                    'July',
                    style: TextStyle(
                      fontSize: 18,
                      fontFamily: 'Avenir',
                      fontWeight: FontWeight.w400,
                      height: 57,
                      letterSpacing: -0.11,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 255,
                top: 843,
                child: SizedBox(
                  width: 154,
                  height: 95,
                  child: Text(
                    'Sport',
                    style: TextStyle(
                      fontSize: 18,
                      fontFamily: 'Avenir',
                      fontWeight: FontWeight.w400,
                      height: 57,
                      letterSpacing: -0.11,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 842,
                child: SizedBox(
                  width: 154,
                  height: 95,
                  child: Text(
                    'Lamp',
                    style: TextStyle(
                      fontSize: 18,
                      fontFamily: 'Avenir',
                      fontWeight: FontWeight.w400,
                      height: 57,
                      letterSpacing: -0.11,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 52,
                child: Container(
                  width: 241,
                  height: 50,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 14,
                        top: 1,
                        child: SizedBox(
                          width: 227,
                          height: 47,
                          child: Text(
                            'Hayley Barles',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 18,
                              fontFamily: 'Avenir',
                              fontWeight: FontWeight.w800,
                              height: 21.17,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 72,
                        top: 27,
                        child: Text(
                          'hayleybarles@gmail.com',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 13,
                            fontFamily: 'Avenir',
                            fontWeight: FontWeight.w500,
                            letterSpacing: -0.07,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 53,
                          height: 49,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/53x49"),
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -13,
                top: 258,
                child: Container(
                  width: 220,
                  height: 512,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 30,
                        top: 0,
                        child: SizedBox(
                          width: 127,
                          height: 47,
                          child: Text(
                            'Home',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 18,
                              fontFamily: 'Avenir',
                              fontWeight: FontWeight.w800,
                              height: 21.17,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 25,
                        top: 45,
                        child: SizedBox(
                          width: 190,
                          height: 47,
                          child: Text(
                            'Saved Items',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFFB2AEFF),
                              fontSize: 18,
                              fontFamily: 'Avenir',
                              fontWeight: FontWeight.w800,
                              height: 21.17,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 181,
                        child: SizedBox(
                          width: 190,
                          height: 47,
                          child: Text(
                            'Profile',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFFB2AEFF),
                              fontSize: 18,
                              fontFamily: 'Avenir',
                              fontWeight: FontWeight.w800,
                              height: 21.17,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 30,
                        top: 92,
                        child: SizedBox(
                          width: 190,
                          height: 47,
                          child: Text(
                            'App Settings',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFFB2AEFF),
                              fontSize: 18,
                              fontFamily: 'Avenir',
                              fontWeight: FontWeight.w800,
                              height: 21.17,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1,
                        top: 227,
                        child: SizedBox(
                          width: 190,
                          height: 47,
                          child: Text(
                            'Wallet',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFFB2AEFF),
                              fontSize: 18,
                              fontFamily: 'Avenir',
                              fontWeight: FontWeight.w800,
                              height: 21.17,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 6,
                        top: 138,
                        child: SizedBox(
                          width: 190,
                          height: 47,
                          child: Text(
                            'Product',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFFB2AEFF),
                              fontSize: 18,
                              fontFamily: 'Avenir',
                              fontWeight: FontWeight.w800,
                              height: 21.17,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 28,
                        top: 275,
                        child: SizedBox(
                          width: 190,
                          height: 47,
                          child: Text(
                            'Help & FAQs',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFFB2AEFF),
                              fontSize: 18,
                              fontFamily: 'Avenir',
                              fontWeight: FontWeight.w800,
                              height: 21.17,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 68,
                        top: 481,
                        child: SizedBox(
                          width: 121,
                          height: 28,
                          child: Text(
                            'Log Out',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 18,
                              fontFamily: 'Avenir',
                              fontWeight: FontWeight.w800,
                              letterSpacing: 0.18,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 45,
                        top: 485,
                        child: SizedBox(
                          width: 24,
                          height: 27,
                          child: Text(
                            'sign-out-alt',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 14,
                              fontFamily: 'Font Awesome 5 Pro',
                              fontWeight: FontWeight.w900,
                              height: 16.25,
                              letterSpacing: 0.35,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 177,
                top: 104,
                child: Container(
                  width: 399.06,
                  height: 652.19,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 94.08,
                        child: Opacity(
                          opacity: 0.40,
                          child: Transform(
                            transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-0.15),
                            child: Container(
                              width: 259.02,
                              height: 541.83,
                              decoration: ShapeDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/259x542"),
                                  fit: BoxFit.fill,
                                ),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(39),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 44.17,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-0.15),
                          child: Container(
                            width: 294,
                            height: 615,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 0,
                                  top: 0,
                                  child: Transform(
                                    transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-0.15),
                                    child: Container(
                                      width: 294,
                                      height: 615,
                                      decoration: ShapeDecoration(
                                        image: DecorationImage(
                                          image: NetworkImage("https://via.placeholder.com/294x615"),
                                          fit: BoxFit.fill,
                                        ),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(39),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: -3.88,
                                  top: -27.49,
                                  child: Transform(
                                    transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-0.15),
                                    child: Container(
                                      width: 295,
                                      height: 787,
                                      decoration: BoxDecoration(
                                        image: DecorationImage(
                                          image: NetworkImage("https://via.placeholder.com/295x787"),
                                          fit: BoxFit.fill,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}